=begin comment

Knetik Platform API Documentation latest 

This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package KnetikCloud::AccessTokenApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use KnetikCloud::ApiClient;
use KnetikCloud::Configuration;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class   = shift;
    my (%self) = (
        'api_client' => KnetikCloud::ApiClient->instance,
        @_
    );

    #my $self = {
    #    #api_client => $options->{api_client}
    #    api_client => $default_api_client
    #}; 

    bless \%self, $class;

}


#
# get_o_auth_token
#
# Get access token
# 
# @param string $grant_type Grant type (required)
# @param string $client_id The id of the client (required)
# @param string $client_secret The secret key of the client.  Used only with a grant_type of client_credentials (optional)
# @param string $username The username of the client.  Used only with a grant_type of password (optional)
# @param string $password The password of the client.  Used only with a grant_type of password (optional)
{
    my $params = {
    'grant_type' => {
        data_type => 'string',
        description => 'Grant type',
        required => '1',
    },
    'client_id' => {
        data_type => 'string',
        description => 'The id of the client',
        required => '1',
    },
    'client_secret' => {
        data_type => 'string',
        description => 'The secret key of the client.  Used only with a grant_type of client_credentials',
        required => '0',
    },
    'username' => {
        data_type => 'string',
        description => 'The username of the client.  Used only with a grant_type of password',
        required => '0',
    },
    'password' => {
        data_type => 'string',
        description => 'The password of the client.  Used only with a grant_type of password',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_o_auth_token' } = { 
    	summary => 'Get access token',
        params => $params,
        returns => 'OAuth2Resource',
        };
}
# @return OAuth2Resource
#
sub get_o_auth_token {
    my ($self, %args) = @_;

    # verify the required parameter 'grant_type' is set
    unless (exists $args{'grant_type'}) {
      croak("Missing the required parameter 'grant_type' when calling get_o_auth_token");
    }

    # verify the required parameter 'client_id' is set
    unless (exists $args{'client_id'}) {
      croak("Missing the required parameter 'client_id' when calling get_o_auth_token");
    }

    # parse inputs
    my $_resource_path = '/oauth/token';
    $_resource_path =~ s/{format}/json/; # default format to json

    my $_method = 'POST';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/x-www-form-urlencoded');

    # form params
    if ( exists $args{'grant_type'} ) {
                $form_params->{'grant_type'} = $self->{api_client}->to_form_value($args{'grant_type'});
    }
    
    # form params
    if ( exists $args{'client_id'} ) {
                $form_params->{'client_id'} = $self->{api_client}->to_form_value($args{'client_id'});
    }
    
    # form params
    if ( exists $args{'client_secret'} ) {
                $form_params->{'client_secret'} = $self->{api_client}->to_form_value($args{'client_secret'});
    }
    
    # form params
    if ( exists $args{'username'} ) {
                $form_params->{'username'} = $self->{api_client}->to_form_value($args{'username'});
    }
    
    # form params
    if ( exists $args{'password'} ) {
                $form_params->{'password'} = $self->{api_client}->to_form_value($args{'password'});
    }
    
    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw()];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('OAuth2Resource', $response);
    return $_response_object;
}

1;
