=begin comment

Knetik Platform API Documentation latest 

This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package KnetikCloud::AmazonWebServicesS3Api;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use KnetikCloud::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'KnetikCloud::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = KnetikCloud::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# get_download_url
#
# Get a temporary signed S3 URL for download
# 
# @param string $bucket S3 bucket name (optional)
# @param string $path The path to the file relative the bucket (the s3 object key) (optional)
# @param int $expiration The number of seconds this URL will be valid. Default to 60 (optional, default to 60)
{
    my $params = {
    'bucket' => {
        data_type => 'string',
        description => 'S3 bucket name',
        required => '0',
    },
    'path' => {
        data_type => 'string',
        description => 'The path to the file relative the bucket (the s3 object key)',
        required => '0',
    },
    'expiration' => {
        data_type => 'int',
        description => 'The number of seconds this URL will be valid. Default to 60',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_download_url' } = { 
    	summary => 'Get a temporary signed S3 URL for download',
        params => $params,
        returns => 'string',
        };
}
# @return string
#
sub get_download_url {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/amazon/s3/downloadurl';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'bucket'}) {
        $query_params->{'bucket'} = $self->{api_client}->to_query_value($args{'bucket'});
    }

    # query params
    if ( exists $args{'path'}) {
        $query_params->{'path'} = $self->{api_client}->to_query_value($args{'path'});
    }

    # query params
    if ( exists $args{'expiration'}) {
        $query_params->{'expiration'} = $self->{api_client}->to_query_value($args{'expiration'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(oauth2_client_credentials_grant oauth2_password_grant )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('string', $response);
    return $_response_object;
}

#
# get_signed_s3_url
#
# Get a signed S3 URL for upload
# 
# @param string $filename The file name (optional)
# @param string $content_type The content type (optional)
{
    my $params = {
    'filename' => {
        data_type => 'string',
        description => 'The file name',
        required => '0',
    },
    'content_type' => {
        data_type => 'string',
        description => 'The content type',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'get_signed_s3_url' } = { 
    	summary => 'Get a signed S3 URL for upload',
        params => $params,
        returns => 'AmazonS3Activity',
        };
}
# @return AmazonS3Activity
#
sub get_signed_s3_url {
    my ($self, %args) = @_;

    # parse inputs
    my $_resource_path = '/amazon/s3/signedposturl';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type('application/json');

    # query params
    if ( exists $args{'filename'}) {
        $query_params->{'filename'} = $self->{api_client}->to_query_value($args{'filename'});
    }

    # query params
    if ( exists $args{'content_type'}) {
        $query_params->{'content_type'} = $self->{api_client}->to_query_value($args{'content_type'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(oauth2_client_credentials_grant oauth2_password_grant )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('AmazonS3Activity', $response);
    return $_response_object;
}

1;
