=begin comment

Knetik Platform API Documentation latest 

This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package KnetikCloud::Object::CouponItem;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

Knetik Platform API Documentation latest 

This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "KnetikCloud::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'CouponItem',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'additional_properties' => {
    	datatype => 'HASH[string,Property]',
    	base_name => 'additional_properties',
    	description => 'A map of additional properties, keyed on the property name.  Must match the names and types defined in the template for this item type, or be an extra not from the template',
    	format => '',
    	read_only => '',
    		},
    'behaviors' => {
    	datatype => 'ARRAY[Behavior]',
    	base_name => 'behaviors',
    	description => 'The behaviors linked to the item, describing various options and interactions. May not be included in item lists',
    	format => '',
    	read_only => '',
    		},
    'category' => {
    	datatype => 'string',
    	base_name => 'category',
    	description => 'A category for filtering items',
    	format => '',
    	read_only => '',
    		},
    'created_date' => {
    	datatype => 'int',
    	base_name => 'created_date',
    	description => 'The date the item was created, unix timestamp in seconds',
    	format => '',
    	read_only => '',
    		},
    'id' => {
    	datatype => 'int',
    	base_name => 'id',
    	description => 'The id of the item',
    	format => '',
    	read_only => '',
    		},
    'long_description' => {
    	datatype => 'string',
    	base_name => 'long_description',
    	description => 'A long description of the item',
    	format => '',
    	read_only => '',
    		},
    'name' => {
    	datatype => 'string',
    	base_name => 'name',
    	description => 'The name of the item',
    	format => '',
    	read_only => '',
    		},
    'short_description' => {
    	datatype => 'string',
    	base_name => 'short_description',
    	description => 'A short description of the item, max 255 chars',
    	format => '',
    	read_only => '',
    		},
    'sort' => {
    	datatype => 'int',
    	base_name => 'sort',
    	description => 'A number to use in sorting items.  Default 500',
    	format => '',
    	read_only => '',
    		},
    'tags' => {
    	datatype => 'ARRAY[string]',
    	base_name => 'tags',
    	description => 'List of tags used for filtering items',
    	format => '',
    	read_only => '',
    		},
    'template' => {
    	datatype => 'string',
    	base_name => 'template',
    	description => 'An item template this item is validated against.  May be null and no validation of additional_properties will be done.  Default &#x3D; null',
    	format => '',
    	read_only => '',
    		},
    'type_hint' => {
    	datatype => 'string',
    	base_name => 'type_hint',
    	description => 'The type of the item',
    	format => '',
    	read_only => '',
    		},
    'unique_key' => {
    	datatype => 'string',
    	base_name => 'unique_key',
    	description => 'The unique key for the item',
    	format => '',
    	read_only => '',
    		},
    'updated_date' => {
    	datatype => 'int',
    	base_name => 'updated_date',
    	description => 'The date the item was last updated, unix timestamp in seconds',
    	format => '',
    	read_only => '',
    		},
    'displayable' => {
    	datatype => 'boolean',
    	base_name => 'displayable',
    	description => 'Whether or not the item is currently displayable.  Default &#x3D; true',
    	format => '',
    	read_only => '',
    		},
    'geo_country_list' => {
    	datatype => 'ARRAY[string]',
    	base_name => 'geo_country_list',
    	description => 'A list of country ID to include in the blacklist/whitelist geo policy',
    	format => '',
    	read_only => '',
    		},
    'geo_policy_type' => {
    	datatype => 'string',
    	base_name => 'geo_policy_type',
    	description => 'Whether to use the geo_country_list as a black list or white list for item geographical availability',
    	format => '',
    	read_only => '',
    		},
    'shipping_tier' => {
    	datatype => 'int',
    	base_name => 'shipping_tier',
    	description => 'Provides the abstract shipping needs if this item is physical and can be shipped.  A value of zero means no shipping needed.  Default &#x3D; 0',
    	format => '',
    	read_only => '',
    		},
    'skus' => {
    	datatype => 'ARRAY[Sku]',
    	base_name => 'skus',
    	description => 'The skus for the item. Each defines a unique configuration for the item to be purchased (Large-Blue, Small-Green, etc). These are what is ultimately selected in the store and added to the cart',
    	format => '',
    	read_only => '',
    		},
    'store_end' => {
    	datatype => 'int',
    	base_name => 'store_end',
    	description => 'The date the item will leave the store, unix timestamp in seconds.  If set to null, item will never leave the store',
    	format => '',
    	read_only => '',
    		},
    'store_start' => {
    	datatype => 'int',
    	base_name => 'store_start',
    	description => 'The date the item will appear in the store, unix timestamp in seconds.  If set to null, item will appear in store immediately',
    	format => '',
    	read_only => '',
    		},
    'vendor_id' => {
    	datatype => 'int',
    	base_name => 'vendor_id',
    	description => 'The vendor who provides the item',
    	format => '',
    	read_only => '',
    		},
    'coupon_type_hint' => {
    	datatype => 'string',
    	base_name => 'coupon_type_hint',
    	description => 'The type of coupon',
    	format => '',
    	read_only => '',
    		},
    'discount_max' => {
    	datatype => 'double',
    	base_name => 'discount_max',
    	description => 'The amount this coupon is maxed out at.  Applies if coupon_type_hint is coupon_cart',
    	format => '',
    	read_only => '',
    		},
    'discount_min_cart_value' => {
    	datatype => 'double',
    	base_name => 'discount_min_cart_value',
    	description => 'The minimium amount needed in the cart for the coupon to apply.  Applies if coupon_type_hint is coupon_cart',
    	format => '',
    	read_only => '',
    		},
    'discount_type' => {
    	datatype => 'string',
    	base_name => 'discount_type',
    	description => 'The type of discount in terms of how it deducts price. Value based discount not available for coupon_cart type coupons',
    	format => '',
    	read_only => '',
    		},
    'discount_value' => {
    	datatype => 'double',
    	base_name => 'discount_value',
    	description => 'The amount the coupon will discount the item. If discount_type is &#39;value&#39; this will be a flat amount of currency. If discount type is &#39;percentage&#39; this will be a fraction (0.2 for 20% off) multiplied by the price of the matching item or items.',
    	format => '',
    	read_only => '',
    		},
    'exclusive' => {
    	datatype => 'boolean',
    	base_name => 'exclusive',
    	description => 'Whether this coupon is exclusive or not (true means cannot be in same cart as another).  Default &#x3D; false',
    	format => '',
    	read_only => '',
    		},
    'item_id' => {
    	datatype => 'int',
    	base_name => 'item_id',
    	description => 'The id of the item the coupon is applied to.  Applies if coupon_type_hint is coupon_single_item or coupon_voucher',
    	format => '',
    	read_only => '',
    		},
    'max_quantity' => {
    	datatype => 'int',
    	base_name => 'max_quantity',
    	description => 'The maximum quantity of items the coupon can apply to, null if no limit and minimum 1 otherwise.  Applies if coupon_type_hint is coupon_single_item or coupon_voucher',
    	format => '',
    	read_only => '',
    		},
    'self_exclusive' => {
    	datatype => 'boolean',
    	base_name => 'self_exclusive',
    	description => 'Whether this coupon is exclusive to itself or not (true means cannot add two of this same coupon to the same cart).  Default &#x3D; false',
    	format => '',
    	read_only => '',
    		},
    'valid_for_tags' => {
    	datatype => 'ARRAY[string]',
    	base_name => 'valid_for_tags',
    	description => 'A list of tags for a coupon.  The coupon can only apply to an item that has at least one of these tags.  Applies if coupon_type_hint is coupon_tag',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'additional_properties' => 'HASH[string,Property]',
    'behaviors' => 'ARRAY[Behavior]',
    'category' => 'string',
    'created_date' => 'int',
    'id' => 'int',
    'long_description' => 'string',
    'name' => 'string',
    'short_description' => 'string',
    'sort' => 'int',
    'tags' => 'ARRAY[string]',
    'template' => 'string',
    'type_hint' => 'string',
    'unique_key' => 'string',
    'updated_date' => 'int',
    'displayable' => 'boolean',
    'geo_country_list' => 'ARRAY[string]',
    'geo_policy_type' => 'string',
    'shipping_tier' => 'int',
    'skus' => 'ARRAY[Sku]',
    'store_end' => 'int',
    'store_start' => 'int',
    'vendor_id' => 'int',
    'coupon_type_hint' => 'string',
    'discount_max' => 'double',
    'discount_min_cart_value' => 'double',
    'discount_type' => 'string',
    'discount_value' => 'double',
    'exclusive' => 'boolean',
    'item_id' => 'int',
    'max_quantity' => 'int',
    'self_exclusive' => 'boolean',
    'valid_for_tags' => 'ARRAY[string]'
} );

__PACKAGE__->attribute_map( {
    'additional_properties' => 'additional_properties',
    'behaviors' => 'behaviors',
    'category' => 'category',
    'created_date' => 'created_date',
    'id' => 'id',
    'long_description' => 'long_description',
    'name' => 'name',
    'short_description' => 'short_description',
    'sort' => 'sort',
    'tags' => 'tags',
    'template' => 'template',
    'type_hint' => 'type_hint',
    'unique_key' => 'unique_key',
    'updated_date' => 'updated_date',
    'displayable' => 'displayable',
    'geo_country_list' => 'geo_country_list',
    'geo_policy_type' => 'geo_policy_type',
    'shipping_tier' => 'shipping_tier',
    'skus' => 'skus',
    'store_end' => 'store_end',
    'store_start' => 'store_start',
    'vendor_id' => 'vendor_id',
    'coupon_type_hint' => 'coupon_type_hint',
    'discount_max' => 'discount_max',
    'discount_min_cart_value' => 'discount_min_cart_value',
    'discount_type' => 'discount_type',
    'discount_value' => 'discount_value',
    'exclusive' => 'exclusive',
    'item_id' => 'item_id',
    'max_quantity' => 'max_quantity',
    'self_exclusive' => 'self_exclusive',
    'valid_for_tags' => 'valid_for_tags'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
