=begin comment

Knetik Platform API Documentation latest 

This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
package KnetikCloud::Object::CouponDefinition;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#
#
# NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
# REF: https://github.com/swagger-api/swagger-codegen
#

=begin comment

Knetik Platform API Documentation latest 

This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by the swagger code generator program. 
# Do not edit the class manually.
# Ref: https://github.com/swagger-api/swagger-codegen
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('swagger_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use swagger_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->swagger_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "KnetikCloud::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => '',
                                  class => 'CouponDefinition',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'code' => {
    	datatype => 'string',
    	base_name => 'code',
    	description => 'A unique identifier for the discount. Can be used to remove the discount, and uniqueness within the cart will be enforced.',
    	format => '',
    	read_only => '',
    		},
    'description' => {
    	datatype => 'string',
    	base_name => 'description',
    	description => 'A description for the discount.',
    	format => '',
    	read_only => '',
    		},
    'discount_type' => {
    	datatype => 'string',
    	base_name => 'discount_type',
    	description => 'The type of discount in terms of how it deducts price.',
    	format => '',
    	read_only => '',
    		},
    'exclusive' => {
    	datatype => 'boolean',
    	base_name => 'exclusive',
    	description => 'Whether this discount is exclusive and cannot be used in conjunction with other discounts/coupons. default&#x3D;false',
    	format => '',
    	read_only => '',
    		},
    'max_discount' => {
    	datatype => 'double',
    	base_name => 'max_discount',
    	description => 'For coupon_cart, a minimum total price that the cart must meet to be valid.',
    	format => '',
    	read_only => '',
    		},
    'max_quantity' => {
    	datatype => 'int',
    	base_name => 'max_quantity',
    	description => 'The maximum number of items to count this discount for (not for cart_coupon).',
    	format => '',
    	read_only => '',
    		},
    'min_cart_total' => {
    	datatype => 'double',
    	base_name => 'min_cart_total',
    	description => 'For coupon_cart, a minimum total price that the cart must meet to be valid.',
    	format => '',
    	read_only => '',
    		},
    'name' => {
    	datatype => 'string',
    	base_name => 'name',
    	description => 'A name for the discount.',
    	format => '',
    	read_only => '',
    		},
    'self_exclusive' => {
    	datatype => 'boolean',
    	base_name => 'self_exclusive',
    	description => 'Whether this coupon is exclusive to itself or not (true means cannot add two of this same coupon to the same cart).  Default &#x3D; false',
    	format => '',
    	read_only => '',
    		},
    'target_item_id' => {
    	datatype => 'int',
    	base_name => 'target_item_id',
    	description => 'The id of the item this discount applies to, which must be present in the cart. Applies if coupon_type_hint is coupon_single_item or coupon_voucher.',
    	format => '',
    	read_only => '',
    		},
    'type' => {
    	datatype => 'string',
    	base_name => 'type',
    	description => 'The type of discount in terms of what it applies to. coupon_cart applies to the cart as a whole, other types apply to specific items based on different criteria.',
    	format => '',
    	read_only => '',
    		},
    'unique_key' => {
    	datatype => 'string',
    	base_name => 'unique_key',
    	description => 'A unique identifier string for the discount.',
    	format => '',
    	read_only => '',
    		},
    'valid_for_tags' => {
    	datatype => 'ARRAY[string]',
    	base_name => 'valid_for_tags',
    	description => 'Which tags this applies for (item must have at least one of them), if coupon_type is coupon_tag.',
    	format => '',
    	read_only => '',
    		},
    'value' => {
    	datatype => 'double',
    	base_name => 'value',
    	description => 'The amount of the discount. If discount_type is value then this is the raw currency amount to remove. If discount_type is percentage then this will be multiplied by the cart total or item price to get the discount amount (0.5 is half price).',
    	format => '',
    	read_only => '',
    		},
    'vendor_id' => {
    	datatype => 'int',
    	base_name => 'vendor_id',
    	description => 'Which vendor this applies for, if coupon_type is coupon_vendor.',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->swagger_types( {
    'code' => 'string',
    'description' => 'string',
    'discount_type' => 'string',
    'exclusive' => 'boolean',
    'max_discount' => 'double',
    'max_quantity' => 'int',
    'min_cart_total' => 'double',
    'name' => 'string',
    'self_exclusive' => 'boolean',
    'target_item_id' => 'int',
    'type' => 'string',
    'unique_key' => 'string',
    'valid_for_tags' => 'ARRAY[string]',
    'value' => 'double',
    'vendor_id' => 'int'
} );

__PACKAGE__->attribute_map( {
    'code' => 'code',
    'description' => 'description',
    'discount_type' => 'discount_type',
    'exclusive' => 'exclusive',
    'max_discount' => 'max_discount',
    'max_quantity' => 'max_quantity',
    'min_cart_total' => 'min_cart_total',
    'name' => 'name',
    'self_exclusive' => 'self_exclusive',
    'target_item_id' => 'target_item_id',
    'type' => 'type',
    'unique_key' => 'unique_key',
    'valid_for_tags' => 'valid_for_tags',
    'value' => 'value',
    'vendor_id' => 'vendor_id'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
