=begin comment

Knetik Platform API Documentation latest 

This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('KnetikCloud::AuthClientsApi');

my $api = KnetikCloud::AuthClientsApi->new();
isa_ok($api, 'KnetikCloud::AuthClientsApi');

#
# create_client test
#
{
    my $client_resource = undef; # replace NULL with a proper value
    my $result = $api->create_client(client_resource => $client_resource);
}

#
# delete_client test
#
{
    my $client_key = undef; # replace NULL with a proper value
    my $result = $api->delete_client(client_key => $client_key);
}

#
# get_client test
#
{
    my $client_key = undef; # replace NULL with a proper value
    my $result = $api->get_client(client_key => $client_key);
}

#
# get_client_grant_types test
#
{
    my $result = $api->get_client_grant_types();
}

#
# get_clients test
#
{
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $order = undef; # replace NULL with a proper value
    my $result = $api->get_clients(size => $size, page => $page, order => $order);
}

#
# set_client_grant_types test
#
{
    my $client_key = undef; # replace NULL with a proper value
    my $grant_list = undef; # replace NULL with a proper value
    my $result = $api->set_client_grant_types(client_key => $client_key, grant_list => $grant_list);
}

#
# set_client_redirect_uris test
#
{
    my $client_key = undef; # replace NULL with a proper value
    my $redirect_list = undef; # replace NULL with a proper value
    my $result = $api->set_client_redirect_uris(client_key => $client_key, redirect_list => $redirect_list);
}

#
# update_client test
#
{
    my $client_key = undef; # replace NULL with a proper value
    my $client_resource = undef; # replace NULL with a proper value
    my $result = $api->update_client(client_key => $client_key, client_resource => $client_resource);
}


1;
