=begin comment

Knetik Platform API Documentation latest 

This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('KnetikCloud::MediaArtistsApi');

my $api = KnetikCloud::MediaArtistsApi->new();
isa_ok($api, 'KnetikCloud::MediaArtistsApi');

#
# add_artist test
#
{
    my $artist_resource = undef; # replace NULL with a proper value
    my $result = $api->add_artist(artist_resource => $artist_resource);
}

#
# create_artist_template test
#
{
    my $artist_template_resource = undef; # replace NULL with a proper value
    my $result = $api->create_artist_template(artist_template_resource => $artist_template_resource);
}

#
# delete_artist test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->delete_artist(id => $id);
}

#
# delete_artist_template test
#
{
    my $id = undef; # replace NULL with a proper value
    my $cascade = undef; # replace NULL with a proper value
    my $result = $api->delete_artist_template(id => $id, cascade => $cascade);
}

#
# get_artist test
#
{
    my $id = undef; # replace NULL with a proper value
    my $show_contributions = undef; # replace NULL with a proper value
    my $result = $api->get_artist(id => $id, show_contributions => $show_contributions);
}

#
# get_artist_template test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->get_artist_template(id => $id);
}

#
# get_artist_templates test
#
{
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $order = undef; # replace NULL with a proper value
    my $result = $api->get_artist_templates(size => $size, page => $page, order => $order);
}

#
# get_artists test
#
{
    my $filter_artists_by_name = undef; # replace NULL with a proper value
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $order = undef; # replace NULL with a proper value
    my $result = $api->get_artists(filter_artists_by_name => $filter_artists_by_name, size => $size, page => $page, order => $order);
}

#
# update_artist test
#
{
    my $id = undef; # replace NULL with a proper value
    my $artist_resource = undef; # replace NULL with a proper value
    my $result = $api->update_artist(id => $id, artist_resource => $artist_resource);
}

#
# update_artist_template test
#
{
    my $id = undef; # replace NULL with a proper value
    my $artist_template_resource = undef; # replace NULL with a proper value
    my $result = $api->update_artist_template(id => $id, artist_template_resource => $artist_template_resource);
}


1;
