=begin comment

Knetik Platform API Documentation latest 

This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::MessagingApi');

my $api = WWW::SwaggerClient::MessagingApi->new();
isa_ok($api, 'WWW::SwaggerClient::MessagingApi');

#
# send_raw_email test
#
{
    my $raw_email_resource = undef; # replace NULL with a proper value
    my $result = $api->send_raw_email(raw_email_resource => $raw_email_resource);
}

#
# send_raw_sms test
#
{
    my $raw_sms_resource = undef; # replace NULL with a proper value
    my $result = $api->send_raw_sms(raw_sms_resource => $raw_sms_resource);
}

#
# send_templated_email test
#
{
    my $message_resource = undef; # replace NULL with a proper value
    my $result = $api->send_templated_email(message_resource => $message_resource);
}

#
# send_templated_sms test
#
{
    my $template_sms_resource = undef; # replace NULL with a proper value
    my $result = $api->send_templated_sms(template_sms_resource => $template_sms_resource);
}


1;
