=begin comment

Knetik Platform API Documentation latest 

This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('KnetikCloud::ReportingUsageApi');

my $api = KnetikCloud::ReportingUsageApi->new();
isa_ok($api, 'KnetikCloud::ReportingUsageApi');

#
# get_usage_by_day test
#
{
    my $start_date = undef; # replace NULL with a proper value
    my $end_date = undef; # replace NULL with a proper value
    my $combine_endpoints = undef; # replace NULL with a proper value
    my $method = undef; # replace NULL with a proper value
    my $url = undef; # replace NULL with a proper value
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $result = $api->get_usage_by_day(start_date => $start_date, end_date => $end_date, combine_endpoints => $combine_endpoints, method => $method, url => $url, size => $size, page => $page);
}

#
# get_usage_by_hour test
#
{
    my $start_date = undef; # replace NULL with a proper value
    my $end_date = undef; # replace NULL with a proper value
    my $combine_endpoints = undef; # replace NULL with a proper value
    my $method = undef; # replace NULL with a proper value
    my $url = undef; # replace NULL with a proper value
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $result = $api->get_usage_by_hour(start_date => $start_date, end_date => $end_date, combine_endpoints => $combine_endpoints, method => $method, url => $url, size => $size, page => $page);
}

#
# get_usage_by_minute test
#
{
    my $start_date = undef; # replace NULL with a proper value
    my $end_date = undef; # replace NULL with a proper value
    my $combine_endpoints = undef; # replace NULL with a proper value
    my $method = undef; # replace NULL with a proper value
    my $url = undef; # replace NULL with a proper value
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $result = $api->get_usage_by_minute(start_date => $start_date, end_date => $end_date, combine_endpoints => $combine_endpoints, method => $method, url => $url, size => $size, page => $page);
}

#
# get_usage_by_month test
#
{
    my $start_date = undef; # replace NULL with a proper value
    my $end_date = undef; # replace NULL with a proper value
    my $combine_endpoints = undef; # replace NULL with a proper value
    my $method = undef; # replace NULL with a proper value
    my $url = undef; # replace NULL with a proper value
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $result = $api->get_usage_by_month(start_date => $start_date, end_date => $end_date, combine_endpoints => $combine_endpoints, method => $method, url => $url, size => $size, page => $page);
}

#
# get_usage_by_year test
#
{
    my $start_date = undef; # replace NULL with a proper value
    my $end_date = undef; # replace NULL with a proper value
    my $combine_endpoints = undef; # replace NULL with a proper value
    my $method = undef; # replace NULL with a proper value
    my $url = undef; # replace NULL with a proper value
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $result = $api->get_usage_by_year(start_date => $start_date, end_date => $end_date, combine_endpoints => $combine_endpoints, method => $method, url => $url, size => $size, page => $page);
}

#
# get_usage_endpoints test
#
{
    my $start_date = undef; # replace NULL with a proper value
    my $end_date = undef; # replace NULL with a proper value
    my $result = $api->get_usage_endpoints(start_date => $start_date, end_date => $end_date);
}


1;
