=begin comment

Knetik Platform API Documentation latest 

This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com

OpenAPI spec version: latest 
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::StoreVendorsApi');

my $api = WWW::SwaggerClient::StoreVendorsApi->new();
isa_ok($api, 'WWW::SwaggerClient::StoreVendorsApi');

#
# create_vendor test
#
{
    my $vendor = undef; # replace NULL with a proper value
    my $result = $api->create_vendor(vendor => $vendor);
}

#
# delete_vendor test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->delete_vendor(id => $id);
}

#
# get_vendor test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->get_vendor(id => $id);
}

#
# get_vendors test
#
{
    my $filter_name = undef; # replace NULL with a proper value
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $order = undef; # replace NULL with a proper value
    my $result = $api->get_vendors(filter_name => $filter_name, size => $size, page => $page, order => $order);
}

#
# update_vendor test
#
{
    my $id = undef; # replace NULL with a proper value
    my $vendor = undef; # replace NULL with a proper value
    my $result = $api->update_vendor(id => $id, vendor => $vendor);
}


1;
