=begin comment

Knetik Platform API Documentation Latest

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: Latest
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::TaxesApi');

my $api = WWW::SwaggerClient::TaxesApi->new();
isa_ok($api, 'WWW::SwaggerClient::TaxesApi');

#
# create_tax_using_post test
#
{
    my $country_code_iso3 = undef; # replace NULL with a proper value
    my $tax_resource = undef; # replace NULL with a proper value
    my $result = $api->create_tax_using_post(country_code_iso3 => $country_code_iso3, tax_resource => $tax_resource);
}

#
# delete_tax_using_delete test
#
{
    my $country_code_iso3 = undef; # replace NULL with a proper value
    my $result = $api->delete_tax_using_delete(country_code_iso3 => $country_code_iso3);
}

#
# delete_tax_using_delete1 test
#
{
    my $country_code_iso3 = undef; # replace NULL with a proper value
    my $state_code = undef; # replace NULL with a proper value
    my $result = $api->delete_tax_using_delete1(country_code_iso3 => $country_code_iso3, state_code => $state_code);
}

#
# get_all_taxes_using_get test
#
{
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $order = undef; # replace NULL with a proper value
    my $result = $api->get_all_taxes_using_get(size => $size, page => $page, order => $order);
}

#
# get_tax_using_get test
#
{
    my $country_code_iso3 = undef; # replace NULL with a proper value
    my $result = $api->get_tax_using_get(country_code_iso3 => $country_code_iso3);
}

#
# get_tax_using_get1 test
#
{
    my $country_code_iso3 = undef; # replace NULL with a proper value
    my $state_code = undef; # replace NULL with a proper value
    my $result = $api->get_tax_using_get1(country_code_iso3 => $country_code_iso3, state_code => $state_code);
}

#
# get_taxes_using_get test
#
{
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $order = undef; # replace NULL with a proper value
    my $result = $api->get_taxes_using_get(size => $size, page => $page, order => $order);
}

#
# get_taxes_using_get1 test
#
{
    my $country_code_iso3 = undef; # replace NULL with a proper value
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $order = undef; # replace NULL with a proper value
    my $result = $api->get_taxes_using_get1(country_code_iso3 => $country_code_iso3, size => $size, page => $page, order => $order);
}

#
# update_tax_using_post test
#
{
    my $tax_resource = undef; # replace NULL with a proper value
    my $result = $api->update_tax_using_post(tax_resource => $tax_resource);
}

#
# update_tax_using_put test
#
{
    my $country_code_iso3 = undef; # replace NULL with a proper value
    my $tax_resource = undef; # replace NULL with a proper value
    my $result = $api->update_tax_using_put(country_code_iso3 => $country_code_iso3, tax_resource => $tax_resource);
}

#
# update_tax_using_put1 test
#
{
    my $country_code_iso3 = undef; # replace NULL with a proper value
    my $state_code = undef; # replace NULL with a proper value
    my $tax_resource = undef; # replace NULL with a proper value
    my $result = $api->update_tax_using_put1(country_code_iso3 => $country_code_iso3, state_code => $state_code, tax_resource => $tax_resource);
}


1;
