=begin comment

Knetik Platform API Documentation Latest

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: Latest
Contact: support@knetik.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::UsersGroupsApi');

my $api = WWW::SwaggerClient::UsersGroupsApi->new();
isa_ok($api, 'WWW::SwaggerClient::UsersGroupsApi');

#
# add_group_using_post test
#
{
    my $group_resource = undef; # replace NULL with a proper value
    my $result = $api->add_group_using_post(group_resource => $group_resource);
}

#
# add_member_using_post test
#
{
    my $unique_name = undef; # replace NULL with a proper value
    my $username = undef; # replace NULL with a proper value
    my $result = $api->add_member_using_post(unique_name => $unique_name, username => $username);
}

#
# create_group_template_using_post test
#
{
    my $group_template_resource = undef; # replace NULL with a proper value
    my $result = $api->create_group_template_using_post(group_template_resource => $group_template_resource);
}

#
# delete_group_template_using_delete test
#
{
    my $id = undef; # replace NULL with a proper value
    my $cascade = undef; # replace NULL with a proper value
    my $result = $api->delete_group_template_using_delete(id => $id, cascade => $cascade);
}

#
# delete_group_using_delete test
#
{
    my $unique_name = undef; # replace NULL with a proper value
    my $user_id = undef; # replace NULL with a proper value
    my $result = $api->delete_group_using_delete(unique_name => $unique_name, user_id => $user_id);
}

#
# delete_group_using_delete1 test
#
{
    my $unique_name = undef; # replace NULL with a proper value
    my $result = $api->delete_group_using_delete1(unique_name => $unique_name);
}

#
# get_group_template_using_get test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->get_group_template_using_get(id => $id);
}

#
# get_group_templates_using_get test
#
{
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $order = undef; # replace NULL with a proper value
    my $result = $api->get_group_templates_using_get(size => $size, page => $page, order => $order);
}

#
# get_group_using_get test
#
{
    my $unique_name = undef; # replace NULL with a proper value
    my $result = $api->get_group_using_get(unique_name => $unique_name);
}

#
# search_groups_using_get test
#
{
    my $unique_name = undef; # replace NULL with a proper value
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $order = undef; # replace NULL with a proper value
    my $result = $api->search_groups_using_get(unique_name => $unique_name, size => $size, page => $page, order => $order);
}

#
# search_groups_using_get1 test
#
{
    my $size = undef; # replace NULL with a proper value
    my $page = undef; # replace NULL with a proper value
    my $order = undef; # replace NULL with a proper value
    my $result = $api->search_groups_using_get1(size => $size, page => $page, order => $order);
}

#
# update_group_template_using_put test
#
{
    my $id = undef; # replace NULL with a proper value
    my $group_template_resource = undef; # replace NULL with a proper value
    my $result = $api->update_group_template_using_put(id => $id, group_template_resource => $group_template_resource);
}

#
# update_group_using_put test
#
{
    my $unique_name = undef; # replace NULL with a proper value
    my $group_resource = undef; # replace NULL with a proper value
    my $result = $api->update_group_using_put(unique_name => $unique_name, group_resource => $group_resource);
}

#
# update_member_status_using_put test
#
{
    my $unique_name = undef; # replace NULL with a proper value
    my $user_id = undef; # replace NULL with a proper value
    my $status = undef; # replace NULL with a proper value
    my $result = $api->update_member_status_using_put(unique_name => $unique_name, user_id => $user_id, status => $status);
}


1;
